### ISSUE TITLE
introduce qualified parse events and link to generation/download events

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#33]
Currently, download/generation events are explicitly linked to crawl events by the "usedBy" relationship ship . 

We'd like introduce a uuid to reference a parse event (e.g., RSS reader) to the downloading of the content referenced resulting from the parsed RSS .

**Comment by jhpoelen** [comment]
Pseudo rdf/nquads

```
<some parse event uuid> <wasInformedBy> <some RSS download event uuid> .
<some parse event uuid> <used> <some content hash> .
....
<some content hash> <hasMember> <some url> .
<some url> <hasVersion> <hash://sha256/abc...> .
<some download event uuid> <generated> <hash://sha256/abc...> .
<some download event uuid> <wasInformedBy> <some parse event uuid>
```

**Comment by jhpoelen** [comment]
We need a way for parsers (aka statement listeners) to register their parse events so that the archiver (aka downloader/dereferencer) can related specific download events to the events that triggered them (or were informed by them). 
```
<_:blank> <http://www.w3.org/ns/prov#qualifiedGeneration> <285cef08-fcfc-4acd-bf51-c1f73d283f72> .
<285cef08-fcfc-4acd-bf51-c1f73d283f72> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Generation> .
<285cef08-fcfc-4acd-bf51-c1f73d283f72> <http://www.w3.org/ns/prov#wasInformedBy> <parse event uuid> .
<285cef08-fcfc-4acd-bf51-c1f73d283f72> <http://www.w3.org/ns/prov#used> <https://example.org/data> .
<https://example.org/data> <http://purl.org/pav/hasVersion> <_:blank> .
```

**Comment by jhpoelen** [comment]
solution - let the parse submit a batch of statement so that the archiver can handle them send this along to next parser. The next parse now has the information about the event that generated the content so it can related it's parsing event to that.

**Comment by mielliott** [comment]
Waiting for #41 before introducing parse events

**Comment by mielliott** [comment]
@jhpoelen I'm wondering what your thoughts are on how verbose activity provenance needs to be. At a minimum, only `<activity> <type> <Activity>` needs to be said, and when a source activity exists, we should include `<newActivity> <wasInformedBy> <sourceActivity>`. Should we also include `startedAtTime` and `endedAtTime` statements? I can understand their use for debugging and things, but they don't seem useful all the time, especially for activities that operate on fixed data (referenced by hash). Also, do you know of any other types of statements we should emit?

Should registry readers log an activity even when parsing produces no results? Again, useful for debugging, maybe, but not much value otherwise.

**Comment by mielliott** [comment]
To clarify, logging the start/end times for things like download events are great. Just not sure if we always need to include those times for all activities.

**Comment by jhpoelen** [comment]
@mielliott good point about the logging verbosity. I'd suggest to start with the most minimal solution. We can always move verbose logging later.

**Comment by mielliott** [comment]
Feature added in dcfa07c031595af428a43019614602eb66d7cf2c
