### ISSUE TITLE
Suggestion - replace triples with quads

### ISSUE THREAD

**Issue by mielliott** [bio-guoda/preston#39]
We should replace ```Triple``` with ```Quad``` to allow for tagging statements with the optional graph label available in the n-quads format.

According to https://www.w3.org/TR/n-quads/, the graph label is "an optional optional blank node label or IRI labeling what graph in a dataset the triple belongs to."

**Comment by jhpoelen** [comment]
Hey @mielliott - 

I've made some changes to introduce (graph name / dataset name) support by nquads with some light refactoring. 

I found that the ```QuadLike``` interface extends the ```TripleLike``` interface, not the ```Triple``` interface. The ```QuadLike``` interface is implemented by the ```Quad``` class. So, to get things started, I've introduced ```TripleLike``` interfaces across the code base. Also, the factory used to create statements now produced quads instead of triples, while still returning them as ```TripleLike```-s. By default, you can create a statement with default (or empty) graph name using:

```java
TripleLike statement = RefNodeFactory.createStatement(subj, verb, obj)
``` 
Setting the graph name can be done using:
```
TripleLike statement = RefNodeFactory.createStatementWithGraphName(someIRI, subj, verb, obj)
```

Retrieving the graph name made simple by using:

```java
Optional<BlankNodeOrIRI> graphName = RefNodeFactory.graphNameOf(someTripleLike);
```
Soon, we'd probably want to use the QuadLike interface. 

Also, the logging (nquads + tsv) include the graph name / dataset name.

**Comment by jhpoelen** [comment]
hey @mielliott, I've just completed the interface migrations from TripleLike to Quad . Please comment or re-open is you feel more discussion or work is needed to address this issue.

**Comment by mielliott** [comment]
@jhpoelen I don't see the ```RefNodeFactory.graphNameOf()``` function implemented, did you decide against it? Should I use ```statement.getGraphName()``` instead?

It might be convenient to have graph name retrieval functions that behave in the same fashion as the ```hasVersionStatement``` and ```getVersion``` functions, something like:

```java
public static boolean hasGraphName(Quad statement) {
    return statement.getGraphName().isPresent();
}

public static BlankNodeOrIRI getGraphName(Quad statement) {
    return (statement.getGraphName().orElse(null);
}
```

Especially since ```toStatement``` accepts ```null``` as a graph name. Thoughts?

**Comment by jhpoelen** [comment]
My thoughts are to use the Quad API using ```statement.getGraphName()``` . It seems to me that ```RefNodeFactory.hasGraphName(quad)``` is as compact as ```statement.getGraphName.isPresent()```. Also, the ```<Optional>``` help to understand that the graphname might not be present. But. . . I am happy to be convinced.
