### ISSUE TITLE
rdf statements for describing the generation of a tika-hash

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#65]
With #59 , we introduce the tika-tlsh hash. Now, we'd like to express the generation of such a hash from a sha256 referenced content  in rdf statements.

**Comment by mielliott** [comment]
I stopped `TikaHashingActivity` from emitting `<activityUUID> <used> <hash://sha256/blubbub>` because that statement was causing the activity to keep running in an endless loop. I can't think of a nice way to prevent that statement from running another tika-tlsh hashing activity. The `uses` statement was also a little redundant with `<hash://tika-tlsh/blahblah> <wasDerivedFrom> <hash://sha256S/blubbub> <activityUUID> .`, so I don't think anyone will miss it much. Now we see something like this:
```
<something> <isRelatedTo> <hash://sha256/blabla> .
<3f531feb-6139-4c07-839a-474c3ec8c7ba> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <3f531feb-6139-4c07-839a-474c3ec8c7ba> .
<hash://tika-tlsh/532a4237d1782aa7576f40d213f91ce46b1fb886498bebcedc507680db323a9415f> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/blabla> <3f531feb-6139-4c07-839a-474c3ec8c7ba> .
<hash://tika-tlsh/532a4237d1782aa7576f40d213f91ce46b1fb886498bebcedc507680db323a9415f> <http://www.w3.org/ns/prov#wasGeneratedBy> <3f531feb-6139-4c07-839a-474c3ec8c7ba> <3f531feb-6139-4c07-839a-474c3ec8c7ba> .
```
Also, I stopped the tika-tlsh hashing activity from running when it sees "hash://tika-tlsh/..." in the subject, so the last two lines no longer cause the activity to run again. I'm gonna assume that's good enough for now.

@jhpoelen feel free to close this issue if you don't object to these changes.

**Comment by jhpoelen** [comment]
Hey @mielliott - thanks for having a look at this. Why not simply prevent generated messages from getting inserted into the processing queue and only accept new quads from stdin?

**Comment by mielliott** [comment]
I was reluctant to give up that beautiful feature of preston. If we do that, then the tikatlsh processor still won't be able to play with other processors in the future. I guess that's okay for now though.

Doing what you suggest might look like this:
```java

@Parameters(separators = "= ", commandDescription = "Generates Tika TLSH associated with any encountered hash://sha256 IRIs")
public class CmdTika extends CmdProcess {

    @Override
    protected Stream<StatementListener> createProcessors(BlobStore blobStore, StatementListener queueAsListener) {
        return Stream.empty();
    }

    @Override
    void processQueue(Queue<Quad> statementQueue, BlobStore blobStore, ActivityContext ctx, StatementListener[] listeners) {
        Queue<Quad> generatedQueue = new ConcurrentLinkedQueue<Quad>();

        StatementListener[] processors = Stream.of(
                new TikaHashingActivity(blobStore, generatedQueue::add)
        ).toArray(StatementListener[]::new);

        handleQueuedMessages(statementQueue, listeners);

        StatementEmitter emitter = statement -> {
            handleStatement(statement, listeners);
            handleStatement(statement, processors);
            handleQueuedMessages(statementQueue, listeners);
            handleQueuedMessages(generatedQueue, listeners);
        };
        new EmittingStreamRDF(emitter, this).parseAndEmit(getInputStream());
    }
}
```
It passes the CmdTikaTests. Let me know if you prefer this and I'll make the changes.

**Comment by mielliott** [comment]
Actually, that code does not let `processors` listen in the first pass over `statementQueue`. I'll fix that. You get the idea though.

**Comment by jhpoelen** [comment]
Thanks for sharing the example. I see the tika-tlsh processor independent from how the queue is managed, so you'd still be able to use the processor in other commands / workflows. I'll have a look at the implementation shortly and hoping to discuss in today's meeting.

**Comment by mielliott** [comment]
> I see the tika-tlsh processor independent from how the queue is managed, so you'd still be able to use the processor in other commands / workflows

But it explodes if it reads from the same queue that it writes to. If we use the tika-tlsh processor in the `update` or `process` commands, it will explode. Right? Looking forward to discussing this.

**Comment by jhpoelen** [comment]
I think some context is needed for the Activity to be somewhat smart about making a decision to process or not. Perhaps if we emit a graph (a collection of related statements) instead of individual statements, an activity like TikaTLSH can decide to not process statement originating from a named graph that was produced by that same TikaTLSH in the past.

So, instead of:

```java
Quad statement = ...
something.emit(statement)
```

we'd say:

```java
Graph<Quad> graph = ...
something.emit(graph)
```

or similarly:

```java
List<Quad> statements = ...
something.emit(statements)
```

**Comment by mielliott** [comment]
I'm all for that. We discussed something very similar in the past when trying to link activities with `wasInformedBy` statements, but I don't think we had considered that it could address some recursive loop issues.

Since all of our processors group their generated statements as inputs to a`emitAsNewActivity`/`emitAsNamedActivity` function, we already have a little bit of a batch messaging structure in place.

Note that this would only let us detect "one-step" cycles (A -> A), but we could still have multi-step cycles (A -> B -> A). If we use a `Graph` struct as you proposed, we would have the option of extending it in the future, if needed, to keep some memory to detect multi-step cycles.

**Comment by mielliott** [comment]
Nice! I tried it and got the same output. Closing issue.
