### ISSUE TITLE
suspicious submatch using "[a-zA-Z0-9]+@([a-zA-Z0-9]+\.)+[a-zA-Z0-9]+"

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston#87]
When using regex match below, I expected only single matches (e.g., ```foo@example.org```). However, submatches are also reported (e.g., ```example.```). 

@mielliott Is this expected?

```
$ preston ls | preston match -l tsv [a-zA-Z0-9]+@([a-zA-Z0-9]+\.)+[a-zA-Z0-9]+
...
<cut:hash://sha256/f6a9c77382d8e4efa15236d5ef002d8ba97ecad4b6f1a8dc044053113fee8d25!/b1426-1439> <http://www.w3.org/ns/prov#value> "jbest@brit.org" <7e204192-05aa-4cd7-a3fa-9463a4cc83c2> .
<cut:hash://sha256/f6a9c77382d8e4efa15236d5ef002d8ba97ecad4b6f1a8dc044053113fee8d25!/b1432-1436> <http://www.w3.org/ns/prov#value> "brit." <7e204192-05aa-4cd7-a3fa-9463a4cc83c2> .
<cut:hash://sha256/f6a9c77382d8e4efa15236d5ef002d8ba97ecad4b6f1a8dc044053113fee8d25!/b1426-1439> <http://www.w3.org/ns/prov#hadMember> <cut:hash://sha256/f6a9c77382d8e4efa15236d5ef002d8ba97ecad4b6f1a8dc044053113fee8d25!/b1432-1436> <7e204192-05aa-4cd7-a3fa-9463a4cc83c2> .
...
```

**Comment by mielliott** [comment]
Thanks for trying this out!

What is "correct behavior" is a little up in the air right now. Currently, all capturing groups are reported. They need to be specified non-capturing to be ignored, e.g. `(?>blahblah)` instead of `(blahblah)`. Obviously, marking groups capturing/non-capturing has uses that are completely separate from whether or not we would want to record the submatch, so this is not an ideal solution.

I could restrict it to only report named groups. This is also not a perfect solution -- group names (while not totally necessary) might only be there to make backreferencing easier -- but "report named groups" is probably be a better rule than "report capturing groups". A less confusing approach might be to specify groups to report by name as an option to `preston match`, e.g. `preston match -g group1,group2,group3`, and/or have an option to report all (named?) submatches.

In any case, whatever we decide on should definitely make its way to the `match` help section.

Thoughts?

**Comment by jhpoelen** [comment]
Thanks for elaborating. I suggest to leave as is right now.
